name = "ResurgenceRP_Dev"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = "ResurgenceRP Mod (DEV)"; // tool tip on mouse hover
overview = "Some first mod overview"; // overview
action = "https://dayz.com/"; // link
author = "ResurgenceRP"; // author
version = "1.1"; // version